version: '3.8'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      # Declarando variaveis de ambiente que são usadas na build da api 
      - DB_HOST=postgres
      - DB_NAME=my_db
      - DB_PASS=password123
      - DB_USER=userino
    ports:
      - 5000:5000
    networks:
      - backend
    depends_on:
      - postgres


  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile  
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password123 
      POSTGRES_USER: userino 
    networks:
      - backend  

networks:
    backend:
      driver: bridge